### ISSUE TITLE
Update to latest homebridge and homebridge-ui compatibility

### ISSUE THREAD

**Issue by bbernstein** [bbernstein/homebridge-snowsense#14]
Make it easier for end users to install and configure without needing to edit the config file.

**Comment by scoutbeer** [comment]
Thank you for creating this!  I have the exact same use case.  Was thrilled when i found this plugin.

**Comment by bbernstein** [comment]
I have a PR for a major rewrite. Since I've written this myself, I don't have any code reviewers. If anyone reads this who can take a look at the PR, please let me know and I'll make you a reviewer.

**Comment by bbernstein** [comment]
I have a working version of this on npm as a beta which can be installed as an "alternate".
Click the wrench and select "Install Alternate Version", then select the one that is "2.x... - beta".
I'm running it now, pretending to be in a location where it will be snowing soon that will end later to make sure it can do the full start and stop cycle.

**Comment by scoutbeer** [comment]
Did some testing this morning after seeing your message about the BETA.  I eventually got it to work.  See my process below and what i encountered along the way.

**Errors after upgrading PI to Beta.  Continual HB 1.5.1 restart loop**

```
12/19/2022, 11:47:42 AM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge B019) is running on port 51460.
[12/19/2022, 11:47:44 AM] AxiosError: Request failed with status code 401
    at settle (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/adapters/http.js:505:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Tried upgrading HB to 1.6.0, similar behavior. Then moved it to it's own Child Bridge**
   
```
[12/19/2022, 11:58:54 AM] Home bridge v1.6.0 (HAP v0.11.0) (Homebridge B019) is running on port 51460.
[12/19/2022, 11:58:57 AM] [SnowSense] Launched child bridge with PID 2939
[12/19/2022, 11:58:57 AM] Registering platform 'homebridge-snowsense.SnowSense'
[12/19/2022, 11:58:57 AM] [SnowSense] Loaded homebridge-snowsense v2.0.2-beta.3 child bridge successfully
[12/19/2022, 11:58:58 AM] Loaded 1 cached accessories from cachedAccessories.0E73597327F9.
[12/19/2022, 11:58:58 AM] [SnowSense] Finished initializing platform: SnowSense
[12/19/2022, 11:58:58 AM] [SnowSense] Loading accessory from cache: Is Snowy
[12/19/2022, 11:58:58 AM] Publishing bridge accessory (name: SnowSense, publishInfo: {
  username: '0E:73:59:73:27:F9',
  port: 41696,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[12/19/2022, 11:58:58 AM] [SnowSense] Executed didFinishLaunching callback
[12/19/2022, 11:58:58 AM] [SnowSense] Restoring existing accessory from cache: Is Snowy
[12/19/2022, 11:58:58 AM] [SnowSense] Created new SnowyAccessory object: Is Snowy
[12/19/2022, 11:58:58 AM] Homebridge v1.6.0 (HAP v0.11.0) (SnowSense) is running on port 41696.

/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 401
    at settle (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/adapters/http.js:505:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[12/19/2022, 11:58:59 AM] [SnowSense] Child bridge process ended
[12/19/2022, 11:58:59 AM] [SnowSense] Process Ended. Code: 1, Signal: null
[12/19/2022, 11:59:06 AM] [SnowSense] Restarting Process...
[12/19/2022, 11:59:08 AM] [SnowSense] Launched child bridge with PID 3073
12/19/2022, 11:59:08 AM] Registering platform 'homebridge-snowsense.SnowSense'
[12/19/2022, 11:59:08 AM] [SnowSense] Loaded homebridge-snowsense v2.0.2-beta.3 child bridge successfully
[12/19/2022, 11:59:08 AM] Loaded 1 cached accessories from cachedAccessories.0E73597327F9.
[12/19/2022, 11:59:08 AM] [SnowSense] Finished initializing platform: SnowSense
[12/19/2022, 11:59:08 AM] [SnowSense] Loading accessory from cache: Is Snowy
[12/19/2022, 11:59:08 AM] Publishing bridge accessory (name: SnowSense, publishInfo: {
  username: '0E:73:59:73:27:F9',
  port: 41696,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[12/19/2022, 11:59:08 AM] [SnowSense] Executed didFinishLaunching callback
[12/19/2022, 11:59:08 AM] [SnowSense] Restoring existing accessory from cache: Is Snowy
[12/19/2022, 11:59:08 AM] [SnowSense] Created new SnowyAccessory object: Is Snowy
[12/19/2022, 11:59:08 AM] Homebridge v1.6.0 (HAP v0.11.0) (SnowSense) is running on port 41696.

/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/core/settle.js:19
    reject(new AxiosError(
           ^
AxiosError: Request failed with status code 401
    at settle (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-snowsense/node_modules/axios/lib/adapters/http.js:505:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Checked JSON config for the SnowSense PI and saw that old JSON config for the Plugin was still in place.  Stepped through the UI based config to see if it would overwrite the old config**

```
[12/19/2022, 12:04:49 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge B019) is running on port 51460.
[12/19/2022, 12:04:51 PM] [SnowSense] Launched child bridge with PID 3573
[12/19/2022, 12:04:51 PM] Registering platform 'homebridge-snowsense.SnowSense'
[12/19/2022, 12:04:51 PM] [SnowSense] Loaded homebridge-snowsense v2.0.2-beta.3 child bridge successfully
[12/19/2022, 12:04:51 PM] Loaded 1 cached accessories from cachedAccessories.0E73597327F9.
[12/19/2022, 12:04:51 PM] [SnowSense] Finished initializing platform: SnowSense
[12/19/2022, 12:04:51 PM] [SnowSense] Loading accessory from cache: Is Snowy
[12/19/2022, 12:04:51 PM] Publishing bridge accessory (name: SnowSense, publishInfo: {
  username: '0E:73:59:73:27:F9',
  port: 41696,
  pincode: '***-**-***',
  category: 2,
  bind: undefined,
  mdns: undefined,
  addIdentifyingMaterial: true,
  advertiser: undefined
}).
[12/19/2022, 12:04:51 PM] [SnowSense] Executed didFinishLaunching callback
[12/19/2022, 12:04:51 PM] [SnowSense] Restoring existing accessory from cache: Is Snowy
[12/19/2022, 12:04:51 PM] [SnowSense] Created new SnowyAccessory object: Is Snowy
[12/19/2022, 12:04:51 PM] [SnowSense] Fetching new weather
[12/19/2022, 12:04:51 PM] Homebridge v1.6.0 (HAP v0.11.0) (SnowSense) is running on port 41696.
[12/19/2022, 12:04:52 PM] [SnowSense] Cur and 3 hours snow: false,false,false,false
[12/19/2022, 12:04:52 PM] [SnowSense] Snowing now: false, Snowing soon: false, Snowed recently: false
[12/19/2022, 12:04:52 PM] [SnowSense] Last time snow forecasted: [NEVER]
[12/19/2022, 12:04:52 PM] [SnowSense] Updating weather (first time). frequency: 900000
```

**I wanted to call attention to something.  I tried entering few cities by Name, State vs. LONG/LAT, but that the locations i was using did not work.  They were:**
Carrol, IA
Missoula, MT
I had to use the LONG/LAT for these in order for them to work.

**Here is error for Carrol,IA**

```
Error: No location found for city (Carroll, IA)
    at /homebridge/node_modules/homebridge-snowsense/src/SnowForecastService.ts:151:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SnowForecastService.convertLocationToLatLong (/homebridge/node_modules/homebridge-snowsense/src/SnowForecastService.ts:116:12)
    at SnowForecastService.setup (/homebridge/node_modules/homebridge-snowsense/src/SnowForecastService.ts:77:50)
    at SnowWatch.setup (/homebridge/node_modules/homebridge-snowsense/src/SnowWatch.ts:107:5)
    at SnowWatch.readSnowForecast (/homebridge/node_modules/homebridge-snowsense/src/SnowWatch.ts:115:5)
    at SnowWatch.updatePredictionStatus (/homebridge/node_modules/homebridge-snowsense/src/SnowWatch.ts:182:22)
    at Function.updateAccessories (/homebridge/node_modules/homebridge-snowsense/src/platform.ts:70:5)
    at SnowSensePlatform.watchWeather (/homebridge/node_modules/homebridge-snowsense/src/platform.ts:102:5)
    at SnowSensePlatform.startWatchingWeather (/homebridge/node_modules/homebridge-snowsense/src/platform.ts:65:5)
```

My experience summarized is:
The upgrade from the old plugin to the new/beta plugin did not use/convert any of the prior JSON config.  I had to manually configure again using the Visual/UI config.  At that point it over wrote the JSON and worked.  I had trouble with using City, State vs. Long/Lat as noted above.  I did try a more populated well know city (Chicago, IL) and still got a similar error.  

One thing I was hoping for a bit more of an understanding/explanation on is the move from multiple discreet sensors to a single 'IsSnowy' sensor.  It would be great to see a detailed write up in the README or WIKI.

Thanks again for all the work on this PI and now the update as well.  I'll continue to help test as needed.

**Comment by bbernstein** [comment]
Thanks for that detailed report. That's very helpful.

The format expected by the openweathermap api needs a country code, so you would use "Carrol, IA, US". They always assume that the last value is the country, so it can see "Paris, FR" and know which country you are talking about. Maybe I'll add a separate field for the country and just append that to the location. It's safer to use a zip code or even better, latitude/longitude. The old version only accepted lat/lon but now it calls the openweathermap api to convert zip or city to lat/lon.

I'm still doing some testing and the one thing I haven't tested yet is that it will turn off after the expected number of hours after seeing snow. I'll find a place where it will be snowing and see if that works for that location. I'll also need to do some playing with mock timers to be able to add a unit test for that.

Feedback is great and I hope to make it nice and solid soon before the next snow here in Boston.

**Comment by bbernstein** [comment]
I just published 2.0.2-beta.4 to test out latest changes. I added test to verify checking when show ended in the past.

**Comment by bbernstein** [comment]
A note about having separate accessories for "snowing soon", "snowing now", and "snowed recently". I actually have all the code to put them back in, but I thought it might be confusing having extra accessories around. If you find them useful, I can put them back in.

**Comment by scoutbeer** [comment]
> A note about having separate accessories for "snowing soon", "snowing now", and "snowed recently". I actually have all the code to put them back in, but I thought it might be confusing having extra accessories around. If you find them useful, I can put them back in.

I'm probably just not fully understanding the logic behind 'IsSnowy'.  The others are a bit more obvious. 

I'll test 2.0.2-beta.4 and give some feedback when I have some time freed up.

**Comment by bbernstein** [comment]
the "IsSnowy" logic is simply `snowingSoon || snowingNow || snowedRecently`. It just means it's time to turn the mats on when it turns on, and off when it turns off. The others were just more granular but I was never using them directly. All that logic is still in the code but I commented-out the part when I create appliances for each.

On another note, the latest beta seems to be detecting things ok, but if it's already snowing when we start homebridge, it doesn't "change" the characteristic, so it doesn't trigger the Homekit event that indicates that it changed.

I think it needs to start in the 'off' position, and then at the first check, change it to 'on' so that the change triggers an event.

**Comment by bbernstein** [comment]
published beta5 a little while ago. It starts in "off" position before checking for snow the first time when starting homebridge. I'm not sure what's happening in homekit, but it doesn't seem to activate the "when occupancy detected" even when it switches to "on" after it starts. I'm pretending to be in a place where it's going to start in several hours so I can see what happens if it gets switched while it's already running.

**Comment by scoutbeer** [comment]
Ok, just got some time free to test beta6.

My testing config:
Homebridge v1.5.1
SnowSense v1.1.0
All Apple devices (iOS and AppleTV OS) using HomeKit upgraded to v16.2 or MacOS 13.1 
[Homekit NOT upgraded to new Hardware Architecture - Side note: Apple just pulled this upgrade anyway due to bugs/issues]

At the time of doing this upgrade v1.1.0 of the plugin was showing 'WillSnow' and 'IsSnowy' was in 'Occupied' mode based on my locations weather forecast.

Upgraded the plugin directly from 1.1.0 to 2.0.2-beta6
Immediately performed a Restart via the button in the Homebridge UI

LOGS:

> [12/22/2022, 10:21:53 AM] [SnowSense] Initializing SnowSense platform...
> [12/22/2022, 10:21:53 AM] [SnowSense] Finished initializing platform: SnowSense
> [12/22/2022, 10:21:53 AM] [SnowSense] Executed didFinishLaunching callback
> [12/22/2022, 10:21:53 AM] [SnowSense] Adding new accessory: Is Snowy
> [12/22/2022, 10:21:53 AM] [SnowSense] converting city=[New York,NY,US]
> [12/22/2022, 10:21:54 AM] [SnowSense] Error getting updated weather: Request failed with status code 401
> [12/22/2022, 10:21:54 AM] [SnowSense] Updating weather (first time). frequency: 900000

Appears as if plugin defaults were pre-loaded as my old LAT/LONG is gone as well as my API key.  beta6 appears to not convert or import existing settings. [This isn't a big deal, just pointing it out as user experience feedback.]

Manually updated plugin settings via UI to add back my API key and my local LONG/LAT.  
At the time of doing this the local weather was forecasting snow.
Immediately performed a Restart via the button in the Homebridge UI

Logs:

```
[12/22/2022, 10:28:15 AM] [SnowSense] Initializing SnowSense platform...
[12/22/2022, 10:28:15 AM] [SnowSense] Finished initializing platform: SnowSense
[12/22/2022, 10:28:15 AM] [SnowSense] Loading accessory from cache: Is Snowy
[12/22/2022, 10:28:15 AM] [SnowSense] Executed didFinishLaunching callback
[12/22/2022, 10:28:15 AM] [SnowSense] Restoring existing accessory from cache: Is Snowy
[12/22/2022, 10:28:15 AM] [SnowSense] Created new SnowyAccessory object: Is Snowy                    
[12/22/2022, 10:28:15 AM] [SnowSense] Fetching new weather
[12/22/2022, 10:28:16 AM] [SnowSense] Now and next 3 hours: false,false,true,false
[12/22/2022, 10:28:16 AM] [SnowSense] Snow predicted at Thu Dec 22 2022 12:00:00 GMT-0600 (Central Standard Time) (current time is Thu Dec 22 2022 10:28:16 GMT-0600 (Central Standard Time))
[12/22/2022, 10:28:16 AM] [SnowSense] Last time snow forecasted: Thu Dec 22 2022 10:28:16 GMT-0600 (Central Standard Time)
[12/22/2022, 10:28:16 AM] [SnowSense] Snowing now: false, Snowing soon: true, Snowed recently: true
[12/22/2022, 10:28:16 AM] [SnowSense] Setting value of Is Snowy to:  1
[12/22/2022, 10:28:16 AM] [SnowSense] Updating weather (first time). frequency: 900000
```

The sensor immediately showed as occupied which in this case is correct.   We are expecting show through tomorrow so i will reply once I follow the logs and see exactly when the sensor goes back to unoccupied mode.

**Comment by bbernstein** [comment]
Thanks for more detailed feedback. In the latest 2.beta.6 it seems to be working well for me. I'm pretending to be in Montreal, CA where it snowed, then stopped, then started again today and the sensor seems to be going on/off appropriately.

I did not spend time converting the old settings over, but I will do that before an official release. The new settings names are a little less ambiguous, so I did change several of the names. Thanks for the comments about converting over as I hadn't thought much about that.

**Comment by scoutbeer** [comment]
One question I forgot to ask.  I don't think it matters much, just more of a curiosity.

It looks like the current plugin uses the 2.5 API (which i think was the newest at the time you created plugin).  Documentation here: https://openweathermap.org/api/one-call-api

I noticed that Openweather now has a 3.0 API. See docs here: https://openweathermap.org/api/one-call-3

Any value in switching to the 3.0 API?  

One interesting thing I noticed from my Openweather account is that it appears that calls against the 2.5 API do not get counted towards the 1000 calls a day limit.  When I go view my usage stats i see no usage at all.

Also wanted to let you know that it looks like the beta6 did turn off the sensor based on the logs

> [12/23/2022, 2:43:17 AM] [SnowSense] Snowing now: false, Snowing soon: false, Snowed recently: true
> [12/23/2022, 2:58:17 AM] [SnowSense] Updating weather (repeating). frequency: 900000
> [12/23/2022, 2:58:17 AM] [SnowSense] Fetching new weather
> [12/23/2022, 2:58:17 AM] [SnowSense] Now and next 3 hours: false,false,false,false
> [12/23/2022, 2:58:17 AM] [SnowSense] Last time snow forecasted: Thu Dec 22 2022 23:58:17 GMT-0600 (Central Standard Time)
> [12/23/2022, 2:58:17 AM] [SnowSense] Snowing now: false, Snowing soon: false, Snowed recently: true
> [12/23/2022, 3:13:17 AM] [SnowSense] Updating weather (repeating). frequency: 900000
> [12/23/2022, 3:13:17 AM] [SnowSense] Fetching new weather
> [12/23/2022, 3:13:17 AM] [SnowSense] Now and next 3 hours: false,false,false,false
> [12/23/2022, 3:13:17 AM] [SnowSense] Last time snow forecasted: Thu Dec 22 2022 23:58:17 GMT-0600 (Central Standard Time)
> [12/23/2022, 3:13:17 AM] [SnowSense] Snowing now: false, Snowing soon: false, Snowed recently: false
> [12/23/2022, 3:13:17 AM] [SnowSense] Setting value of Is Snowy to:  0

**Comment by bbernstein** [comment]
That's interesting that 2.5 calls don't get counted. I didn't actually spend any time looking at the differences in the api but I just copied the logic from the old version.

Today I'll work on getting the app to read the legacy configs. I'll take a look at the api and maybe switch to 3.0 if there's a chance that 2.5 may get deprecated.

**Comment by scoutbeer** [comment]
I thought it was strange too that no usage was shown.  Maybe sanity check your account and see what comes up.  This is what I see:

![OW_usage](https://user-images.githubusercontent.com/87205579/209381710-eed73f7a-957a-4259-ac5c-91ae8b931796.png)

**Comment by bbernstein** [comment]
I just tested api 3.0 and it threw a 401 error with this message:

```
  "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."
```

So, it seems that an upgrade would require users to go back to openweathermap and sign up for the 3.0 api. I may do it anyway, but just sharing that even with updating the configs, the user will need to take an action if I update the api level.

Thanks for pointing it out. I hadn't looked to see that there was a new version.

**Comment by bbernstein** [comment]
Here is the api call I'm using (fill in your api key). I subscribed to 3.0 but it's not working for me. I guess that's why they have a phone number to call. Try this with 2.5 and 3.0 with your key to see if one or the other or both work for you. That is just the last part of the url from `/2.5/onecall?` to `/3.0/onecall?`
```
https://api.openweathermap.org/data/2.5/onecall?lat=45.5031824&lon=-73.5698065&appid=YOUR_KEY_HERE&units=imperial&exclude=minutely,alerts,daily
```

**Comment by scoutbeer** [comment]
Both 2.5 and 3.0 work for me using the example URL you provided plus my own key.  
Worth noting, when I first signed up for OneCall and it gave me 3.0 access it took several hours for it to start working.  I was running into the same 401 error out of the gate.  Eventually it started to work.

**Comment by scoutbeer** [comment]
and now that i've played with the 3.0 API usage info is showing....

![OW3_usage](https://user-images.githubusercontent.com/87205579/209401133-ab411ae6-264f-4289-9e78-cd6cb0981880.png)

**Comment by bbernstein** [comment]
Yup, after a little while the 3.0 version started working. I don't remember what info I gave when I signed up a few years ago, but I imagine all new accounts are using 3.0 as there's not much reference to 2.5 anymore.

I should probably update to 3.0 and add more info to the message if it receives a 401 error to return to openweathermap and upgrade.

**Comment by bbernstein** [comment]
I am making it an option in configs. It will default to 2.5 to stay backward-compatible, but in the configs I added the ability to choose between 2.5 and 3.0.
A new beta will be coming out shortly.

**Comment by bbernstein** [comment]
I just published a new beta: v2.0.2-beta.7
It imports all settings from v1 and defaults to api 2.5 but has a config to choose 3.0.

**Comment by thewolfanator** [comment]
Hi, I feel like I am missing something really simple but can't figure it out.  Getting this error:
I have a valid API key.

[12/25/2022, 3:31:03 PM] [Snow Sense] Error getting updated weather: Error getting weather from OpenWeatherMap: Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.

**Comment by bbernstein** [comment]
> Hi, I feel like I am missing something really simple but can't figure it out. Getting this error: I have a valid API key.
> 
> [12/25/2022, 3:31:03 PM] [Snow Sense] Error getting updated weather: Error getting weather from OpenWeatherMap: Invalid API key. Please see https://openweathermap.org/faq#error401 for more info.

It looks like your key is not valid. If you just got a new key, it may take a few hours before it starts working (see above when I had that same problem). You can test your api key by entering this url with your key.

It's possible that your api key is only good for one of the versions. In the latest beta it lets you choose between v2.5 and v3.0.

Try your key with each of he url's below (replace "YOUR_API_KEY" with your actual key.
If one of them works, but not the other, let us know which one works. If you try the latest beta version, then you can try using that.

Here is a sample call to openweathermap api v2.5
```
https://api.openweathermap.org/data/3.0/onecall?lat=43.6166163&lon=-116.200886&units=imperial&exclude=minutely,alerts,daily&appid=YOUR_API_KEY
```

This is the same for api v3.0
```
https://api.openweathermap.org/data/2.5/onecall?lat=43.6166163&lon=-116.200886&units=imperial&exclude=minutely,alerts,daily&appid=YOUR_API_KEY
```

**Comment by thewolfanator** [comment]
yes, both give an error. Do I have to subscribe to one call by call plan, I had chosen the free one?

**Comment by bbernstein** [comment]
Yes, apparently it needs a call-by-call plan for it to work. I don't know when that started, but there should be no actual charges as long as you stay under 1000 calls per day. Same as before, but they seem to require a credit card to signup even if there are no charges.

**Comment by bbernstein** [comment]
I did another release of 2.0 beta.8. Nothing to notice, but I found that setting the before/after to zero wasn't working. I fixed that and added more unit tests to make sure zero values work properly.

**Comment by scoutbeer** [comment]
Test upgrade from 1.1.0 to 2.0.2-beta8

Working config:
HB 1.5.1
SnowSense 1.1.0
All Apple devices using HomeKit on 16.2 or MacOS 13.1 [Homekit NOT upgraded to new Hardware Architecture]

At the time of doing this upgrade v1.1.0 of the plugin was showing all 4 sensors in 'Occupied' mode

Upgraded direct from 1.1.0 to 2.0.2-beta8
Immediately performed a Restart via the button in the Homoebridge UI

LOGS:
```
[12/26/2022, 1:23:10 PM] [SnowSense] Initializing SnowSense platform...
[12/26/2022, 1:23:10 PM] [SnowSense] Updating config to new format.  {
  platform: 'SnowSense',
  name: 'SnowSense',
  provider: 'openweathermap',
  key: undefined,
  latitude: undefined,
  longitude: undefined,
  units: 'imperial',
  forecastFrequency: undefined,
  beforeSnowStarts: undefined,
  afterSnowStops: undefined,
  sensors: 'any, past, present, future',
  apiKey: 'KEYxxxxxxx',
  apiVersion: '2.5',
  location: '42.976,-78.792',
  hoursBeforeSnowIsSnowy: 3,
  hoursAfterSnowIsSnowy: 3,
  apiThrottleMinutes: 15
}
[12/26/2022, 1:23:10 PM] [SnowSense] Finished initializing platform: SnowSense
[12/26/2022, 1:23:10 PM] [SnowSense] Executed didFinishLaunching callback
[12/26/2022, 1:23:10 PM] [SnowSense] Adding new accessory: Is Snowy
[12/26/2022, 1:23:11 PM] [SnowSense] Fetching new weather
[12/26/2022, 1:23:13 PM] [SnowSense] Now and next 3 hours: true,true,true,true
[12/26/2022, 1:23:13 PM] [SnowSense] Snow predicted in -23.224766666666667 minutes
[12/26/2022, 1:23:13 PM] [SnowSense] Last predicted: Mon Dec 26 2022 13:23:13 GMT-0600 (Central Standard Time) (0 minutes ago), expires in 180 minutes
[12/26/2022, 1:23:13 PM] [SnowSense] Snowing now: true, Snowing soon: true, Snowed recently: true
[12/26/2022, 1:23:13 PM] [SnowSense] Setting value of Is Snowy to:  1
[12/26/2022, 1:23:13 PM] [SnowSense] Updating weather (first time). frequency: 900000
```

It looks like the existing configuration was successfully converted to the new Visual/UI Config with API 2.5 being used as the default.  Also looks like the upgrade cleaned up the 4 old sensors and is not just using the single 'IsSnowy' sensor.

Changed the API setting to 3.0 in the visual config, saved and manually restarted via button in UI

Logs:

```
[12/26/2022, 1:27:30 PM] [SnowSense] Initializing SnowSense platform...
[12/26/2022, 1:27:30 PM] [SnowSense] Finished initializing platform: SnowSense
[12/26/2022, 1:27:30 PM] [SnowSense] Loading accessory from cache: Is Snowy
[12/26/2022, 1:27:30 PM] [SnowSense] Executed didFinishLaunching callback
[12/26/2022, 1:27:30 PM] [SnowSense] Restoring existing accessory from cache: Is Snowy
[12/26/2022, 1:27:30 PM] [SnowSense] Created new SnowyAccessory object: Is Snowy
[12/26/2022, 1:27:30 PM] [SnowSense] Fetching new weather
[12/26/2022, 1:27:31 PM] [SnowSense] Now and next 3 hours: true,true,true,true
[12/26/2022, 1:27:31 PM] [SnowSense] Snow predicted in -27.53098333333333 minutes
[12/26/2022, 1:27:31 PM] [SnowSense] Last predicted: Mon Dec 26 2022 13:27:31 GMT-0600 (Central Standard Time) (0.000016666666666666667 minutes ago), expires in 179.99998333333332 minutes
[12/26/2022, 1:27:31 PM] [SnowSense] Snowing now: true, Snowing soon: true, Snowed recently: true
[12/26/2022, 1:27:31 PM] [SnowSense] Setting value of Is Snowy to:  1
[12/26/2022, 1:27:31 PM] [SnowSense] Updating weather (first time). frequency: 900000
```

Looks like API 2.5 and 3.0 are working well with respect to initial config and setup.

**Comment by bbernstein** [comment]
Thanks for the detailed feedback. 

It looks like it's working for you. 

I changed some of the debug output to give some clearer info so that seems right. The "snow predicted in -27.5 minutes" is probably the time of the first hourly forecast which is at the top of the current hour, so seeing your log showing it is 1:27, that prediction was in the past. That shouldn't be an issue though, but just thought I'd point it out.

I may make 2.0 an official release soon, so let me know if you find any issues.

I appreciate your help.

**Comment by bbernstein** [comment]
I made an official release: v2.0.2, which is now the default version.
Thanks for all your help while I put this together.
If there are any issues, please open a new [issue](https://github.com/bbernstein/homebridge-snowsense/issues) and I'll follow up.

**Comment by scoutbeer** [comment]
Happy to help!  I just upgraded to v2.0.2 from the old 1.x version.  Upgrade itself went well, settings were converted and the new 'IsSnowy' sensor was created.  The only thing i did notice was that the four old sensors were still showing in the Homebridge Accessories page.  I rebooted the entire Homebridge server and upon reboot the old accessories were cleared.

**Comment by bbernstein** [comment]
Thanks again for all the help. This new version started off as my experimenting with ChatGBT and github CoPilot, and I ended up doing a full rewrite with some AI help. The ChatGBT usage was pretty minimal, like identifying a "lat,long" pair vs zip code. But Github copilot did a great job autocompleting whole blocks of code mostly pretty well.
